#pragma once
#define VERSION_MAJOR 0
#define VERSION_MINOR 4
#define VERSION_PATCH 0
#define VERSION_STABLE "alpha"
#include "utils.h"
#if VERSION_PATCH
#   define VERSION_STR STRINGIFY2(VERSION_MAJOR) "." STRINGIFY2(VERSION_MINOR) "." STRINGIFY2(VERSION_PATCH)
#else
#   define VERSION_STR STRINGIFY2(VERSION_MAJOR) "." STRINGIFY2(VERSION_MINOR)
#endif
